name: APK_Uretici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTML_to_APK
        uses: darkshredder/website-to-apk-action@v1.0.1
        with:
          app-name: "ACR Security"
          build-folder-path: "."
      - name: APK_Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: ACR_Uygulamam
          path: apk/
